name: py39
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - backcall=0.2.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - comm=0.2.2
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - debugpy=1.8.11
  - decorator=5.2.1
  - entrypoints=0.4
  - executing=2.1.0
  - ffmpeg=4.3
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.12.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.2.5.30
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.2.1
  - numpy-base=1.26.4
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.2.2
      - astunparse==1.6.3
      - attrs==25.3.0
      - charset-normalizer==3.4.1
      - check-shapes==1.1.1
      - cloudpickle==3.1.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - deprecated==1.2.18
      - dm-tree==0.1.8
      - dropstackframe==0.1.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - gast==0.6.0
      - google-pasta==0.2.0
      - gpflow==2.9.2
      - gpytorch==1.13
      - grpcio==1.71.0
      - h5py==3.13.0
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - jaxtyping==0.2.19
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - keras==3.9.2
      - kiwisolver==1.4.7
      - lark==1.2.2
      - libclang==18.1.1
      - linear-operator==0.5.3
      - markdown==3.8
      - markdown-it-py==3.0.0
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - multipledispatch==1.0.0
      - namex==0.0.9
      - narwhals==1.36.0
      - nbformat==5.10.4
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opt-einsum==3.4.0
      - optree==0.15.0
      - pandas==2.2.3
      - pillow==11.2.1
      - plotly==6.0.1
      - protobuf==5.29.4
      - pyparsing==3.2.3
      - pytz==2025.2
      - referencing==0.36.2
      - rich==14.0.0
      - rpds-py==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-probability==0.25.0
      - termcolor==3.0.1
      - tf-keras==2.19.0
      - threadpoolctl==3.6.0
      - torch==2.7.0
      - triton==3.3.0
      - typeguard==4.4.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - zipp==3.21.0
